version: 1.0.{build}
image: Visual Studio 2017
environment:
  DESTDIR: inst
  MSYS: winsymlinks:nativestrict
  SHELL_CANDIDATES: busybox
build_script:
- cmd: >-
    appveyor DownloadFile https://frippery.org/files/busybox/busybox.exe -FileName ../busybox.exe

    set PATH=C:\msys64\usr\bin;%PATH%;%cd%\..

    C:\msys64\usr\bin\bash do install
artifacts:
- path: inst/usr
  name: Built files for windows