version: 1.0.{build}
image:
- Visual Studio 2017
- Ubuntu
environment:
  DESTDIR: inst
build_script:
- cmd: >-
    appveyor DownloadFile https://frippery.org/files/busybox/busybox.exe

    set MSYS=winsymlinks:nativestrict

    set SHELL_CANDIDATES=busybox

    set PATH=C:\msys64\usr\bin;%PATH%;%cd%

    bash do install

    set PATH=%PATH%;%cd%\inst\usr\bin

    cd t

    redo all
- sh: ./do -j10 test
artifacts:
- path: inst/usr
  name: Built files for windows
